library(dplyr)
power<- read.table("./ExData_Plotting1/household_power_consumption.txt",skip = 1,sep = ";")
names(power)
head(power,16)
colnames(power)<- c("date", "Time","Global_active","Global_reactive","Voltage","Global_intencity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
tbl_df(power)
outcome<- filter(power, date %in% c("1/2/2007","2/2/2007"))
outcome$Specific <- strptime(paste(outcome$date,outcome$Time), format="%d/%m/%Y %H:%M:%S") 

par(mfcol= c(2,2))
with(outcome,(plot(Specific, as.numeric(as.character(Global_active)), type="l", xlab="", ylab="Global Active Power")))
with(outcome, {plot(Specific, as.numeric(as.character(Sub_metering_1)), type = "l", xlab = "",ylab = "Energy sub metering")
        lines(Specific, as.numeric(as.character(Sub_metering_2)),type="l", col = "red")
        lines(Specific, as.numeric(as.character(Sub_metering_3)),type="l", col = "blue")
        legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"),lwd = 2.5,cex = 0.5)})
with(outcome,(plot(Specific, as.numeric(as.character(Voltage)), type="l", xlab="date time" , ylab = "Voltage")))
with(outcome,(plot(Specific,as.numeric(as.character(Global_reactive)),xlab="date time" , ylab = "Global_reactive_power",type = "l")))
